INSERT INTO bears (name) VALUES ('bear1'), ('bear2'), ('bear3'), ('bear4'), ('bear1'), ('bear2'), ('bear3'), (NULL)
-- INSERT INTO bears (name) VALUES ('bear1')
-- INSERT INTO bears (name) VALUES ('bear2')
-- INSERT INTO bears (name) VALUES ('bear3')
-- INSERT INTO bears (name) VALUES ('bear4')
-- INSERT INTO bears (name) VALUES ('bear5')
-- INSERT INTO bears (name) VALUES ('bear6')
-- INSERT INTO bears (name) VALUES ('bear7')
-- INSERT INTO bears (name) VALUES ('bear8')